### ISSUE TITLE
Publish on Crates.io

### ISSUE THREAD

**Issue by jonahbron** [Rahix/avr-device#14]
Are there plans to publish each chip as packages to Crates.io?  Or are we waiting until the project is more stable?

**Comment by Rahix** [comment]
Yes, the plan is to publish this crate (and all the generated code in it) once the basic API choices have been battle tested.  The biggest blocker right now is probably the missing interrupt handler implementation (#1).

**Comment by Rahix** [comment]
Let's keep this issue open to track the effort.

**Comment by Rahix** [comment]
Any other things we should definitely do before publishing?

From my side, the only missing thing is the `#[entry]` macro and a little more documentation.

**Comment by jonahbron** [comment]
I think with the entry macro we're good to go.  I want to try to implement SPI this week/weekend, but that's not a blocker.  It's still useful and stable without it.

**Comment by Rahix** [comment]
And it is done! :confetti_ball:

https://crates.io/crates/avr-device
