### ISSUE TITLE
Fails to compile with custom toolchain.

### ISSUE THREAD

**Issue by Altaflux** [Rahix/avr-device#20]
I believe this line is accidentally forcing the nightly toolchain instead of using the default one of rustup.

https://github.com/Rahix/avr-device/blob/5cbb4d85122ad18a05e60af4bccae030057968f4/Makefile#L43

**Comment by Rahix** [comment]
This is intentional as you will usually not have `rustfmt` installed for the avr-toolchain.  You need to have nightly `rustfmt` installed for this build-system to work:

```bash
rustup component add --toolchain nightly rustfmt
```

**Comment by Altaflux** [comment]
Ok that makes a lot of sense. thanks for improving the docs to make it clearer.
