### ISSUE TITLE
Release 0.2.3

### ISSUE THREAD

**Issue by no111u3** [Rahix/avr-device#58]
I think it's time to release 0.2.3 because we have some fixes of register bitfields and other updates.
Thanks

**Comment by Rahix** [comment]
[0.2.3 was released 5 days ago](https://github.com/Rahix/avr-device/blob/v0.2.3/CHANGELOG.md#023---2020-10-19) and there weren't any changes to master since ... Not sure what you mean?

**Comment by no111u3** [comment]
Really sorry about that, I skip some days.

**Comment by Rahix** [comment]
Nothing to be sorry about!  Btw, you can subscribe to new releases in the repository via the `Watch` button in the top right (select `Releases Only`).  Then you will get a notification whenever a new release is published.
