### ISSUE TITLE
alternative source for atdf files

### ISSUE THREAD

**Issue by khimaros** [Rahix/avr-device#61]
https://github.com/avr-rust/avr-mcu/tree/master/packs

would it make sense to deduplicate?

**Comment by Rahix** [comment]
I quite like having the files vendored here.  It's simpler than adding a submodule and having to keeping track of that, we're free in updating/adding/removing individual files, and I would argue the files aren't big enough to warrant caring too much about this.

**Comment by khimaros** [comment]
in that case, maybe worth documenting the source i mentioned?

navigating the atmel site is a bit frustrating and i failed to locate the atdf for at90usb1286

**Comment by Rahix** [comment]
Done :)
