### ISSUE TITLE
Patch-file needed, else "No rule to make target..."

### ISSUE THREAD

**Issue by trembel** [Rahix/avr-device#65]
Trying to integrate the `attiny412`, whilest executing `make` I got the error `make: *** No rule to make target 'src/devices/attiny412/mod.rs', needed by 'attiny412'.  Stop.`.

After creating the file `patch/attiny412.yaml` with following content
```
_svd: ../svd/attiny412.svd
```

Is it possible that a patch file must always be created? If so, this should be added to the `README.md`

**Comment by Rahix** [comment]
> Is it possible that a patch file must always be created? If so, this should be added to the README.md

Yeah, it seems that right now this is required ... I wasn't able to find out why exactly, make magic is a mess ...

But you're right, this should be documented!
