### ISSUE TITLE
Need write access to PRR register in atmega328p

### ISSUE THREAD

**Issue by gpgreen** [Rahix/avr-device#72]
The vendor provided svd for atmega328p lists the PRR register as read only. The access needs to be read/write so that the peripherals can be powered down.

I will create a pull request to fix this issue, however it is not ready to go yet. I am getting an error in the build when i try to use it, and am not experienced enough in rust to decipher it yet.

**Comment by Rahix** [comment]
Please post error messages, otherwise I have no clue what might be going on :)
